on:
  push:
  pull_request:
jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - env:
          DAKI_API_TOKEN: ${{ secrets.DAKI_API_TOKEN }}
        run: |
          pip install requests
          python daki-api.py
